FROM harbor.baai.ac.cn/flagbase/flagbase-nvidia:latest

# noninteractive to make apt-get work
ENV DEBIAN_FRONTEND=noninteractive

# workdir
WORKDIR /workspace
COPY . /workspace/FlagGems
WORKDIR /workspace/FlagGems

# build
RUN pip install -r flag_tree_requirements/requirements_nvidia.txt --break-system-packages
RUN pip install --no-build-isolation . --break-system-packages
